//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.03 at 07:37:45 AM IST 
//


package in.rkvsraman.ocr.olena.scribocli;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the in.rkvsraman.ocr.olena.scribocli package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: in.rkvsraman.ocr.olena.scribocli
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PcGts }
     * 
     */
    public PcGts createPcGts() {
        return new PcGts();
    }

    /**
     * Create an instance of {@link PcGts.Page }
     * 
     */
    public PcGts.Page createPcGtsPage() {
        return new PcGts.Page();
    }

    /**
     * Create an instance of {@link PcGts.Page.WhitespaceSeparatorRegion }
     * 
     */
    public PcGts.Page.WhitespaceSeparatorRegion createPcGtsPageWhitespaceSeparatorRegion() {
        return new PcGts.Page.WhitespaceSeparatorRegion();
    }

    /**
     * Create an instance of {@link PcGts.Page.WhitespaceSeparatorRegion.Coords }
     * 
     */
    public PcGts.Page.WhitespaceSeparatorRegion.Coords createPcGtsPageWhitespaceSeparatorRegionCoords() {
        return new PcGts.Page.WhitespaceSeparatorRegion.Coords();
    }

    /**
     * Create an instance of {@link PcGts.Page.HorizontalSeparatorRegion }
     * 
     */
    public PcGts.Page.HorizontalSeparatorRegion createPcGtsPageHorizontalSeparatorRegion() {
        return new PcGts.Page.HorizontalSeparatorRegion();
    }

    /**
     * Create an instance of {@link PcGts.Page.HorizontalSeparatorRegion.Coords }
     * 
     */
    public PcGts.Page.HorizontalSeparatorRegion.Coords createPcGtsPageHorizontalSeparatorRegionCoords() {
        return new PcGts.Page.HorizontalSeparatorRegion.Coords();
    }

    /**
     * Create an instance of {@link PcGts.Page.VerticalSeparatorRegion }
     * 
     */
    public PcGts.Page.VerticalSeparatorRegion createPcGtsPageVerticalSeparatorRegion() {
        return new PcGts.Page.VerticalSeparatorRegion();
    }

    /**
     * Create an instance of {@link PcGts.Page.VerticalSeparatorRegion.Coords }
     * 
     */
    public PcGts.Page.VerticalSeparatorRegion.Coords createPcGtsPageVerticalSeparatorRegionCoords() {
        return new PcGts.Page.VerticalSeparatorRegion.Coords();
    }

    /**
     * Create an instance of {@link PcGts.Page.ImageRegion }
     * 
     */
    public PcGts.Page.ImageRegion createPcGtsPageImageRegion() {
        return new PcGts.Page.ImageRegion();
    }

    /**
     * Create an instance of {@link PcGts.Page.ImageRegion.Coords }
     * 
     */
    public PcGts.Page.ImageRegion.Coords createPcGtsPageImageRegionCoords() {
        return new PcGts.Page.ImageRegion.Coords();
    }

    /**
     * Create an instance of {@link PcGts.Page.TextRegion }
     * 
     */
    public PcGts.Page.TextRegion createPcGtsPageTextRegion() {
        return new PcGts.Page.TextRegion();
    }

    /**
     * Create an instance of {@link PcGts.Page.TextRegion.Line }
     * 
     */
    public PcGts.Page.TextRegion.Line createPcGtsPageTextRegionLine() {
        return new PcGts.Page.TextRegion.Line();
    }

    /**
     * Create an instance of {@link PcGts.Page.TextRegion.Line.Coords }
     * 
     */
    public PcGts.Page.TextRegion.Line.Coords createPcGtsPageTextRegionLineCoords() {
        return new PcGts.Page.TextRegion.Line.Coords();
    }

    /**
     * Create an instance of {@link PcGts.Page.TextRegion.Coords }
     * 
     */
    public PcGts.Page.TextRegion.Coords createPcGtsPageTextRegionCoords() {
        return new PcGts.Page.TextRegion.Coords();
    }

    /**
     * Create an instance of {@link PcGts.Metadata }
     * 
     */
    public PcGts.Metadata createPcGtsMetadata() {
        return new PcGts.Metadata();
    }

    /**
     * Create an instance of {@link PcGts.Page.WhitespaceSeparatorRegion.Coords.Point }
     * 
     */
    public PcGts.Page.WhitespaceSeparatorRegion.Coords.Point createPcGtsPageWhitespaceSeparatorRegionCoordsPoint() {
        return new PcGts.Page.WhitespaceSeparatorRegion.Coords.Point();
    }

    /**
     * Create an instance of {@link PcGts.Page.HorizontalSeparatorRegion.Coords.Point }
     * 
     */
    public PcGts.Page.HorizontalSeparatorRegion.Coords.Point createPcGtsPageHorizontalSeparatorRegionCoordsPoint() {
        return new PcGts.Page.HorizontalSeparatorRegion.Coords.Point();
    }

    /**
     * Create an instance of {@link PcGts.Page.VerticalSeparatorRegion.Coords.Point }
     * 
     */
    public PcGts.Page.VerticalSeparatorRegion.Coords.Point createPcGtsPageVerticalSeparatorRegionCoordsPoint() {
        return new PcGts.Page.VerticalSeparatorRegion.Coords.Point();
    }

    /**
     * Create an instance of {@link PcGts.Page.ImageRegion.Coords.Point }
     * 
     */
    public PcGts.Page.ImageRegion.Coords.Point createPcGtsPageImageRegionCoordsPoint() {
        return new PcGts.Page.ImageRegion.Coords.Point();
    }

    /**
     * Create an instance of {@link PcGts.Page.TextRegion.Line.Coords.Point }
     * 
     */
    public PcGts.Page.TextRegion.Line.Coords.Point createPcGtsPageTextRegionLineCoordsPoint() {
        return new PcGts.Page.TextRegion.Line.Coords.Point();
    }

    /**
     * Create an instance of {@link PcGts.Page.TextRegion.Coords.Point }
     * 
     */
    public PcGts.Page.TextRegion.Coords.Point createPcGtsPageTextRegionCoordsPoint() {
        return new PcGts.Page.TextRegion.Coords.Point();
    }

}
